APP_TITLE='피수치 가이드 v3.20'
PAGE_TITLE='BloodMap v3.20'
MADE_BY='제작: Hoya/GPT'
CAFE_LINK_MD='[피수치 가이드 공식카페](https://cafe.naver.com/bloodmap)'
FOOTER_CAFE='공식카페: cafe.naver.com/bloodmap'
DISCLAIMER='본 자료는 보호자의 이해를 돕기 위한 참고용입니다.'
FEVER_GUIDE='38.0~38.5℃ 해열제/경과, 38.5℃↑ 병원 연락, 39℃↑ 응급실'
LBL_WBC='WBC'; LBL_Hb='Hb'; LBL_PLT='PLT'; LBL_ANC='ANC'
LBL_Ca='Ca'; LBL_P='P'; LBL_Na='Na'; LBL_K='K'; LBL_Alb='Albumin'
LBL_Glu='Glucose'; LBL_TP='TP'; LBL_AST='AST'; LBL_ALT='ALT'; LBL_LDH='LDH'
LBL_CRP='CRP'; LBL_Cr='Cr'; LBL_UA='UA'; LBL_TB='TB'; LBL_BUN='BUN'; LBL_BNP='BNP'
ORDER=[LBL_WBC,LBL_Hb,LBL_PLT,LBL_ANC,LBL_Ca,LBL_P,LBL_Na,LBL_K,LBL_Alb,LBL_Glu,LBL_TP,LBL_AST,LBL_ALT,LBL_LDH,LBL_CRP,LBL_Cr,LBL_UA,LBL_TB,LBL_BUN,LBL_BNP]
FONT_PATH_REG='fonts/NanumGothic.ttf'
