def interpret_labs(*a, **k): return ['✅ 기본 동작']
def compare_with_previous(*a, **k): return []
def food_suggestions(*a, **k): return []
def summarize_meds(*a, **k): return []
def abx_summary(*a, **k): return []
