def build_report(mode, meta, vals, cmp_lines, extra_vals, meds_lines, food_lines, abx_lines):
    lines=['# 피수치 가이드 보고서','']
    lines.append(f"- 모드: {mode}")
    for k,v in (meta or {}).items():
        if v not in (None,""):
            lines.append(f"- {k}: {v}")
    lines.append('')
    if vals:
        lines.append('## 입력 수치')
        for k,v in vals.items():
            if v is not None and v!='':
                lines.append(f"- {k}: {v}")
    if extra_vals:
        lines.append('\n## 암별 디테일 수치')
        for k,v in extra_vals.items():
            if v is not None and v!='':
                lines.append(f"- {k}: {v}")
    if meds_lines:
        lines.append('\n## 약물 요약'); lines+=["- "+x for x in meds_lines]
    if abx_lines:
        lines.append('\n## 항생제 요약'); lines+=["- "+x for x in abx_lines]
    if food_lines:
        lines.append('\n## 음식 가이드'); lines+=food_lines
    return "\n".join(lines)

def md_to_pdf_bytes_fontlocked(md_text):
    # 더미 PDF 바이트 (실서버 reportlab 사용 권장)
    return b"%PDF-1.4\n%Mock PDF generated by BloodMap placeholder.\n"
