# -*- coding: utf-8 -*-
# 확장 라인업(항암제/항생제)
ANTICANCER = {
    "Cyclophosphamide": {"alias": "사이클로포스파마이드", "aes": ["출혈성 방광염", "골수억제"]},
    "Ifosfamide": {"alias": "이포스파마이드", "aes": ["신경독성", "방광염"]},
    "Melphalan": {"alias": "멜팔란", "aes": ["골수억제", "구내염"]},
    "Busulfan": {"alias": "부설판", "aes": ["폐독성", "경련"]},
    "Temozolomide": {"alias": "테모졸로마이드", "aes": ["골수억제", "오심/구토"]},
    "Cisplatin": {"alias": "시스플라틴", "aes": ["신독성", "이독성", "오심/구토"]},
    "Carboplatin": {"alias": "카보플라틴", "aes": ["골수억제"]},
    "Oxaliplatin": {"alias": "옥살리플라틴", "aes": ["말초신경병증", "한랭유발감각이상"]},
    "5-FU": {"alias": "5-플루오로유라실", "aes": ["점막염", "설사", "수족증후군"]},
    "Capecitabine": {"alias": "카페시타빈", "aes": ["수족증후군", "설사"]},
    "Gemcitabine": {"alias": "젬시타빈", "aes": ["골수억제", "발열"]},
    "Pemetrexed": {"alias": "페메트렉시드", "aes": ["골수억제", "피부발진"]},
    "MTX": {"alias": "메토트렉세이트", "aes": ["간독성", "구내염", "신독성"]},
    "ARA-C": {"alias": "시타라빈", "aes": ["골수억제", "오심/구토", "발열"]},
    "Fludarabine": {"alias": "플루다라빈", "aes": ["면역억제", "감염"]},
    "Irinotecan": {"alias": "이리노테칸", "aes": ["설사(급성/지연)", "골수억제"]},
    "Topotecan": {"alias": "토포테칸", "aes": ["골수억제"]},
    "Etoposide": {"alias": "에토포사이드", "aes": ["골수억제", "저혈압"]},
    "Doxorubicin": {"alias": "독소루비신", "aes": ["심독성", "탈모"]},
    "Daunorubicin": {"alias": "다우노루비신", "aes": ["심독성", "골수억제"]},
    "Epirubicin": {"alias": "에피루비신", "aes": ["심독성"]},
    "Idarubicin": {"alias": "이다루비신", "aes": ["심독성", "골수억제"]},
    "Paclitaxel": {"alias": "파클리탁셀", "aes": ["말초신경병증", "과민반응"]},
    "Docetaxel": {"alias": "도세탁셀", "aes": ["체액저류", "구강점막염"]},
    "Vincristine": {"alias": "빈크리스틴", "aes": ["신경병증", "변비"]},
    "Vinblastine": {"alias": "빈블라스틴", "aes": ["골수억제"]},
    "Tamoxifen": {"alias": "타목시펜", "aes": ["혈전증", "자궁내막암 위험"]},
    "Letrozole": {"alias": "레트로졸", "aes": ["관절통", "골다공증"]},
    "Anastrozole": {"alias": "아나스트로졸", "aes": ["관절통", "골다공증"]},
    "Fulvestrant": {"alias": "풀베스트란트", "aes": ["주사부위통증"]},
    "Imatinib": {"alias": "이마티닙", "aes": ["부종", "피부발진"]},
    "Dasatinib": {"alias": "다사티닙", "aes": ["흉수", "혈소판감소"]},
    "Nilotinib": {"alias": "닐로티닙", "aes": ["QT연장", "고혈당"]},
    "Ponatinib": {"alias": "포나티닙", "aes": ["혈전/혈관사건"]},
    "Sunitinib": {"alias": "수니티닙", "aes": ["고혈압", "피로", "수족증후군"]},
    "Pazopanib": {"alias": "파조파닙", "aes": ["간독성", "고혈압"]},
    "Regorafenib": {"alias": "레고라페닙", "aes": ["수족증후군", "고혈압"]},
    "Lenvatinib": {"alias": "렌바티닙", "aes": ["고혈압", "단백뇨"]},
    "Sorafenib": {"alias": "소라페닙", "aes": ["수족증후군", "고혈압"]},
    "Erlotinib": {"alias": "얼로티닙", "aes": ["피부발진", "설사"]},
    "Gefitinib": {"alias": "게피티닙", "aes": ["피부발진", "설사"]},
    "Osimertinib": {"alias": "오시머티닙", "aes": ["QT연장", "심근염 드묾"]},
    "Alectinib": {"alias": "알렉티닙", "aes": ["근육통", "변비"]},
    "Crizotinib": {"alias": "크리조티닙", "aes": ["시야장애", "부종"]},
    "Brigatinib": {"alias": "브리가티닙", "aes": ["폐독성 초기 증상"]},
    "Trametinib": {"alias": "트라메티닙", "aes": ["피부발진", "심기능저하"]},
    "Dabrafenib": {"alias": "다브라페닙", "aes": ["발열", "관절통"]},
    "Trastuzumab": {"alias": "트라스투주맙", "aes": ["심기능저하"]},
    "Pertuzumab": {"alias": "퍼투주맙", "aes": ["설사", "피로"]},
    "Bevacizumab": {"alias": "베바시주맙", "aes": ["출혈", "고혈압", "창상치유지연"]},
    "Cetuximab": {"alias": "세툭시맙", "aes": ["피부발진", "저마그네슘혈증"]},
    "Panitumumab": {"alias": "파니투무맙", "aes": ["피부발진"]},
    "Rituximab": {"alias": "리툭시맙", "aes": ["주입반응", "HBV재활성"]},
    "Daratumumab": {"alias": "다라투무맙", "aes": ["주입반응"]},
    "Elotuzumab": {"alias": "엘로투주맙", "aes": ["감염 위험"]},
    "Pembrolizumab": {"alias": "펨브롤리주맙", "aes": ["면역관련 이상반응(피부/간/폐/내분비)"]},
    "Nivolumab": {"alias": "니볼루맙", "aes": ["면역관련 이상반응"]},
    "Atezolizumab": {"alias": "아테졸리주맙", "aes": ["면역관련 이상반응"]},
    "Durvalumab": {"alias": "더발루맙", "aes": ["면역관련 이상반응"]},
    "Ipilimumab": {"alias": "이필리무맙", "aes": ["면역관련 대장염/간염"]},
    "ATRA": {"alias": "비스트레티노인", "aes": ["분화증후군", "두통", "피부건조"]},
    "Arsenic trioxide": {"alias": "삼산화비소", "aes": ["QT연장", "분화증후군"]},
    "Hydroxyurea": {"alias": "하이드록시우레아", "aes": ["골수억제", "피부 변화"]},
    "Bortezomib": {"alias": "보르테조밉", "aes": ["말초신경병증", "헤르페스 재활성"]},
    "Carfilzomib": {"alias": "카르필조밉", "aes": ["심부전", "호흡곤란"]},
    "Lenalidomide": {"alias": "레날리도마이드", "aes": ["혈전증", "발진"]},
    "Pomalidomide": {"alias": "포말리도마이드", "aes": ["혈전증", "골수억제"]},
}

ABX_GUIDE = {
    "페니실린": ["과민반응", "설사"],
    "세팔로스포린": ["과민반응", "디설피람 유사 반응(일부)"],
    "카바페넴": ["경련 위험(고용량/신부전)", "광범위 스펙트럼"],
    "모노박탐": ["그람음성 위주", "교차과민 낮음"],
    "글리코펩타이드(반코마이신)": ["신독성", "적정 TDM 필요"],
    "리포글리코펩타이드(테이코플라닌 등)": ["TDM 고려", "피부반응"],
    "옥사졸리디논(리네졸리드)": ["혈소판감소", "세로토닌 증후군"],
    "마크롤라이드": ["QT 연장", "CYP 상호작용"],
    "테트라사이클린": ["광과민", "소아 치아변색"],
    "아미노글리코시드": ["신독성", "이독성"],
    "퀴놀론": ["QT 연장", "힘줄염/파열 위험"],
    "설폰아마이드/트리메토프림": ["과민반응", "고칼륨혈증"],
    "메트로니다졸": ["금주 필요", "금속맛"],
    "클린다마이신": ["C. difficile 대장염 위험"],
    "콜리스틴": ["신경독성/신독성"],
    "다프토마이신": ["CPK 상승", "폐렴엔 비권장"],
    "티지사이클린": ["오심/구토", "범용 사용 주의"],
    "니트로푸란토인": ["폐독성(만성)", "요로감염에 한정"],
}
