# -*- coding: utf-8 -*-
ANTICANCER = {
    "ARA-C": {"alias":"시타라빈"},
    "Daunorubicin": {"alias":"도우노루비신"},
    "Idarubicin": {"alias":"이달루비신"},
    "Cyclophosphamide": {"alias":"사이클로포스파마이드"},
    "Etoposide": {"alias":"에토포사이드"},
    "Fludarabine": {"alias":"플루다라빈"},
    "Hydroxyurea": {"alias":"하이드록시우레아"},
    "MTX": {"alias":"메토트렉세이트"},
    "ATRA": {"alias":"베사노이드(비스트레티노인)"},
    "G-CSF": {"alias":"그라신(필그라스팀)"},
    "Cisplatin":{"alias":"시스플라틴"},
    "Carboplatin":{"alias":"카보플라틴"},
    "Oxaliplatin":{"alias":"옥살리플라틴"},
    "5-FU":{"alias":"플루오로우라실"},
    "Capecitabine":{"alias":"카페시타빈"},
    "Irinotecan":{"alias":"이리노테칸"},
    "Gemcitabine":{"alias":"젬시타빈"},
    "Paclitaxel":{"alias":"파클리탁셀"},
    "Docetaxel":{"alias":"도세탁셀"},
    "Temozolomide":{"alias":"테모졸로마이드"},
    "Bevacizumab":{"alias":"베바시주맙"},
    "Pembrolizumab":{"alias":"펨브롤리주맙"},
    "Nivolumab":{"alias":"니볼루맙"},
    "Trastuzumab":{"alias":"트라스투주맙"},
    "Imatinib":{"alias":"이마티닙"},
    "Dasatinib":{"alias":"다사티닙"},
    "Nilotinib":{"alias":"닐로티닙"},
    "Osimertinib":{"alias":"오시머티닙"},
    "Gefitinib":{"alias":"게피티닙"},
    "Erlotinib":{"alias":"얼로티닙"},
    "Alectinib":{"alias":"알렉티닙"},
    "Sunitinib":{"alias":"수니티닙"},
    "Pazopanib":{"alias":"파조파닙"},
    "Regorafenib":{"alias":"레고라페닙"},
    "Lenvatinib":{"alias":"렌바티닙"},
    "Sorafenib":{"alias":"소라페닙"},
    "Doxorubicin":{"alias":"독소루비신"},
    "Ifosfamide":{"alias":"이포스파마이드"},
    "Vincristine":{"alias":"빈크리스틴"},
    "Asparaginase":{"alias":"아스파라기나제"},
    "Topotecan":{"alias":"토포테칸"},
}

ABX_GUIDE = {
    "페니실린계": ["알레르기 과거력 주의", "고용량 시 경련 위험"],
    "세팔로스포린계": ["페니실린 중증 알레르기 시 교차반응 주의"],
    "카바페넴계": ["발작 위험(고용량/신부전)", "광범위 스펙트럼"],
    "퀴놀론계": ["힘줄염/파열", "QT 연장", "소아·임신부 주의"],
    "마크로라이드계": ["QT 연장", "CYP 상호작용"],
    "아미노글리코사이드계": ["신독성/이독성", "혈중농도 모니터"],
    "테트라사이클린계": ["광과민, 치아변색(소아)"],
    "글리코펩티드(반코마이신)": ["신장/청력 모니터", "적정 농도 유지"],
}

SOLID_BY_CANCER = {
    "폐암(Lung cancer)": ["Cisplatin","Carboplatin","Paclitaxel","Docetaxel","Gemcitabine","Pemetrexed","Gefitinib","Erlotinib","Osimertinib","Alectinib","Bevacizumab","Pembrolizumab","Nivolumab"],
    "유방암(Breast cancer)": ["Doxorubicin","Cyclophosphamide","Paclitaxel","Docetaxel","Trastuzumab","Bevacizumab"],
    "위암(Gastric cancer)": ["Cisplatin","Oxaliplatin","5-FU","Capecitabine","Paclitaxel","Trastuzumab","Pembrolizumab"],
    "대장암(Colorectal cancer)": ["5-FU","Capecitabine","Oxaliplatin","Irinotecan","Bevacizumab"],
    "간암(HCC)": ["Sorafenib","Lenvatinib","Bevacizumab","Pembrolizumab","Nivolumab"],
    "췌장암(Pancreatic cancer)": ["Gemcitabine","Oxaliplatin","Irinotecan","5-FU"],
    "담도암(Cholangiocarcinoma)": ["Gemcitabine","Cisplatin","Bevacizumab"],
    "자궁내막암(Endometrial cancer)": ["Carboplatin","Paclitaxel"],
    "구강암/후두암": ["Cisplatin","5-FU","Docetaxel"],
    "피부암(흑색종)": ["Dacarbazine","Paclitaxel","Nivolumab","Pembrolizumab"],
    "신장암(RCC)": ["Sunitinib","Pazopanib","Bevacizumab","Nivolumab","Pembrolizumab"],
    "갑상선암": ["Lenvatinib","Sorafenib"],
    "난소암": ["Carboplatin","Paclitaxel","Bevacizumab"],
    "자궁경부암": ["Cisplatin","Paclitaxel","Bevacizumab"],
    "전립선암": ["Docetaxel","Cabazitaxel"],
    "뇌종양(Glioma)": ["Temozolomide","Bevacizumab"],
    "식도암": ["Cisplatin","5-FU","Paclitaxel","Nivolumab","Pembrolizumab"],
    "방광암": ["Cisplatin","Gemcitabine","Bevacizumab","Pembrolizumab","Nivolumab"],
}

SARCOMA_DIAG = [
    "골육종(Osteosarcoma)", "유잉육종(Ewing sarcoma)", "횡문근육종(Rhabdomyosarcoma)",
    "평활근육종(Leiomyosarcoma)", "지방육종(Liposarcoma)", "활막육종(Synovial sarcoma)",
    "GIST(위장관기질종양)", "섬유육종(Fibrosarcoma)"
]
SARCOMA_BY_DIAG = {
    "골육종(Osteosarcoma)": ["Doxorubicin","Cisplatin","High-dose MTX","Ifosfamide"],
    "유잉육종(Ewing sarcoma)": ["Vincristine","Doxorubicin","Cyclophosphamide","Ifosfamide","Etoposide"],
    "횡문근육종(Rhabdomyosarcoma)": ["Vincristine","Actinomycin D","Cyclophosphamide","Ifosfamide","Etoposide"],
    "평활근육종(Leiomyosarcoma)": ["Doxorubicin","Ifosfamide","Gemcitabine","Docetaxel","Pazopanib"],
    "지방육종(Liposarcoma)": ["Doxorubicin","Ifosfamide","Eribulin","Trabectedin","Pazopanib"],
    "활막육종(Synovial sarcoma)": ["Ifosfamide","Doxorubicin","Pazopanib"],
    "GIST(위장관기질종양)": ["Imatinib","Sunitinib","Regorafenib"],
    "섬유육종(Fibrosarcoma)": ["Doxorubicin","Ifosfamide"],
}

EXTRA_TESTS_BY_CANCER = {
    "유방암(Breast cancer)": [("CA15-3","U/mL",1),("CEA","ng/mL",1),("HER2(IHC/FISH)","",0),("ER/PR(%)","%",0)],
    "대장암(Colorectal cancer)": [("CEA","ng/mL",1),("CA19-9","U/mL",1)],
    "위암(Gastric cancer)": [("CEA","ng/mL",1),("CA72-4","U/mL",1),("CA19-9","U/mL",1)],
    "간암(HCC)": [("AFP","ng/mL",1),("PIVKA-II(DCP)","mAU/mL",0)],
    "폐암(Lung cancer)": [("CYFRA 21-1","ng/mL",1),("NSE","ng/mL",1),("CEA","ng/mL",1)],
    "피부암(흑색종)": [("S100","µg/L",1),("LDH","U/L",0)],
    "육종(Sarcoma)": [("ALP","U/L",0),("CK","U/L",0),("LDH","U/L",0)],
    "방광암": [("NMP22","U/mL",1),("UBC","µg/L",1)],
    "식도암": [("SCC Ag","ng/mL",1),("CEA","ng/mL",1)],
}

GENERAL_SPECIAL_TESTS = [
    ("C3(보체)", "mg/dL", 1),
    ("C4(보체)", "mg/dL", 1),
    ("CH50(보체총활성)", "U/mL", 1),
    ("요단백(단백뇨)", "mg/dL 또는 Dipstick", 1),
    ("요당", "mg/dL 또는 Dipstick", 1),
    ("요혈(혈뇨)", "Dipstick(음성/추정량)", 1),
    ("요잠혈/적혈구 수", "/HPF", 0),
    ("소변 미세알부민(ACR)", "mg/gCr", 1),
    ("요단백/크레아티닌 비율(UPCR)", "mg/gCr", 1),
]
