[theme]
primaryColor="#1f7aec"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f5f7fb"
textColor="#111111"
font="sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
headless = true